SEQUENCE_LENGTH = 50
EMBEDDING_DIM = 50
FILTER_COUNT = 64
KERNEL_SIZES = [3, 4, 5]
BATCH_SIZE = 32
LEARNING_RATE = 0.001
EPOCHS = 20
DROPOUT_RATE = 0.5
WEIGHT_DECAY = 1e-4
EARLY_STOPPING_PATIENCE = 3
NUM_WORKERS = 0
RANDOM_SEED = 42

DATA_DIR = "data"
SAVED_MODELS_DIR = "saved_models"
RESULTS_DIR = "results"

